# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [2]:
import numpy as np
import random
import scipy.stats as sps
import cv2


### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [3]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.36031703 0.45329212 0.3101684  ... 0.31691205 0.74059653 0.62608638]
 [0.80768064 0.67509331 0.66656443 ... 0.78663644 0.13415205 0.28895965]
 [0.82901214 0.54934259 0.7526258  ... 0.8374212  0.38840667 0.76505486]
 ...
 [0.94655577 0.19939016 0.26361758 ... 0.48917168 0.04856924 0.87153127]
 [0.70992089 0.25786763 0.30143583 ... 0.85836795 0.04632404 0.11320805]
 [0.82806264 0.20678613 0.17931554 ... 0.49852731 0.42961862 0.60155384]]
[[0.28270085 0.59889429 0.29139947 ... 0.697831   0.62602207 0.67277056]
 [0.64627368 0.87444604 0.12130599 ... 0.57543432 0.04483008 0.03005726]
 [0.26617826 0.04749137 0.76381136 ... 0.28154355 0.58201471 0.48315965]
 ...
 [0.86375784 0.5212677  0.38667306 ... 0.31656381 0.56330133 0.47267907]
 [0.37039021 0.7123303  0.91162379 ... 0.45576646 0.44361705 0.73270043]
 [0.78472335 0.68585543 0.75341265 ... 0.46763814 0.8018667  0.72300998]]


Без использования numpy

In [4]:
def mult(a, b):
    if len(a[0]) != len(b):
        print("Невозможно перемножить матрицы: неправильные размеры")
        return None

    result = [[0 for _ in range(len(b[0]))] for _ in range(len(a))]

    for i in range(len(a)):
        for j in range(len(b[0])):
            for k in range(len(b)):
                result[i][j] += a[i][k] * b[k][j]

    return result
result_without_numpy = mult(a.tolist(), b.tolist())
print(result_without_numpy)

[[26.695808444494222, 26.41644496460417, 27.32908268321734, 25.484184603304367, 23.895797999851595, 21.878740977502716, 26.004668689021862, 25.91639006697482, 25.056974874946416, 24.72491490765173, 26.684474706212537, 26.139426043314376, 28.377361829063236, 26.98690521017525, 27.68794010084982, 25.823975266316076, 27.27822906750305, 23.76786513830703, 25.803868629421892, 25.53655692124876, 23.047454876031242, 28.751385595693197, 26.905604060661325, 24.2424529131729, 26.227616253278992, 23.339407679923493, 25.10828858110654, 24.429094109602858, 25.80875347800727, 25.495386037401136, 29.797927770936266, 24.773388275212074, 25.966662193210876, 23.039527613415867, 24.596599815574567, 22.516998640888016, 24.00453006649304, 27.785154311366647, 25.4846412156209, 25.937057403073673, 23.13412044149496, 24.452869891397242, 24.491175470594442, 29.988141745199695, 26.232427446855525, 26.564434288917948, 24.54266444058985, 26.586410893905498, 25.681872652874404, 26.94005164151745, 24.80757270520392

C использованием numpy

In [6]:
def np_mult(a, b):
    result = np.dot(a, b)
    return result

result_np = np_mult(a, b)
print("\nРезультат перемножения с использованием NumPy:")
print(result_np)


Результат перемножения с использованием NumPy:
[[26.69580844 26.41644496 27.32908268 ... 25.56128991 24.81544043
  25.95464372]
 [21.41145652 23.06138057 22.49600109 ... 20.30453213 20.63499381
  19.75340541]
 [24.89350393 23.17684373 23.24042503 ... 20.72602543 22.3509356
  20.81852967]
 ...
 [23.98629709 23.26841917 24.55452631 ... 22.39830291 22.81385468
  23.57970549]
 [25.92809101 24.47346302 23.06232566 ... 22.92988058 22.74400207
  24.78742492]
 [24.9976335  25.97326571 26.40716341 ... 23.38240857 25.09923595
  24.48206593]]


In [7]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 713 ms, sys: 0 ns, total: 713 ms
Wall time: 714 ms


In [8]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 144 µs, sys: 2.08 ms, total: 2.22 ms
Wall time: 1.15 ms


In [9]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.481481604059809e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [10]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.99167028 0.82296056 0.00802343] [0.46342537 0.47687788 0.82981962]


In [15]:
def scalar_product(a,b):
  s = 0
  for i in range(len(a)):
    s += a[i] * b[i]
  return s

result = scalar_product(a, b)

print("Scalar Product:", result)

Scalar Product: 0.858674850087158


In [16]:
def np_scalar_product(a,b):
    s = np.dot(a, b)
    return s
result = np_scalar_product(a, b)
print("Scalar Product:", result)

Scalar Product: 0.858674850087158


In [17]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 23 µs, sys: 5 µs, total: 28 µs
Wall time: 32.7 µs
CPU times: user 53 µs, sys: 0 ns, total: 53 µs
Wall time: 58.2 µs


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:** NumPy является библиотекой для вычислительных операций в Python, специально оптимизированной для работы с многомерными массивами данных Оптимизированные алгоритмы и структуры данных: NumPy использует эффективные алгоритмы и структуры данных для выполнения различных операций, таких как скалярное произведение, умножение матриц, суммирование и другие.

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [21]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
  diagonal_elements = np.diag(a)

  even_diagonal_elements = diagonal_elements[diagonal_elements % 2 == 0]

  return even_diagonal_elements.sum() if even_diagonal_elements.size > 0 else 0

result = np_diag_2k(a)
print(result)

14


In [18]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[5, 2, 8, 3, 4],
       [4, 6, 8, 7, 9],
       [2, 3, 8, 7, 7],
       [7, 1, 7, 7, 4],
       [7, 8, 5, 7, 9]])

In [22]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 121 µs, sys: 0 ns, total: 121 µs
Wall time: 127 µs


14

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [25]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(*A):
  X = np.array(A)
  result = np.cumsum(X, axis=1)
  return result
input_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
output_array = np_sec_av(input_array)

print(output_array)

[[[ 1  2  3]
  [ 5  7  9]
  [12 15 18]]]


In [26]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

[8.05354461e-01 1.59265333e-01 6.56122846e-01 9.71890450e-01
 8.41651077e-01 6.23084475e-01 3.64251608e-02 8.40849849e-01
 1.85793852e-03 8.88918910e-01 7.85412655e-01 1.96267599e-01
 7.70798262e-01 3.35732675e-01 4.25958996e-01 2.56557115e-01
 6.29594815e-02 7.09576103e-01 9.17973972e-02 7.09222845e-01
 5.62713257e-01 9.49110749e-01 6.98227890e-01 4.14841790e-01
 2.24849427e-01 5.13916649e-01 2.72163472e-01 9.69014542e-01
 3.56356453e-01 2.73930991e-01 5.26722258e-01 6.90484577e-01
 7.15757939e-01 2.59021783e-01 5.88716982e-01 7.98357149e-01
 6.90267162e-01 4.40246586e-01 8.49290635e-02 2.03228606e-01
 6.32803966e-01 2.70183199e-01 2.88451960e-01 4.77597915e-01
 6.19976291e-01 2.00209701e-02 3.69889542e-01 4.07577250e-01
 1.25746825e-01 2.68102195e-01 9.74740910e-01 5.73567647e-01
 5.43344571e-01 6.63213885e-01 3.67354712e-01 8.63711836e-01
 9.90737380e-01 9.39219761e-01 8.10481629e-01 2.25691469e-01
 8.70379224e-01 8.90834730e-01 7.43399133e-01 2.57644025e-01
 3.49570534e-01 4.318862

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [29]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
  if len(a) == 0:
    return np.array([]), np.array([])

    change_indices = np.where(a[:-1] != a[1:])[0]

    change_indices = np.concatenate(([change_indices[-1]], change_indices))

    lengths = np.diff(change_indices)

    unique_elements = a[change_indices]

    return unique_elements, lengths


input_array = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
result = np_encode(input_array)
print(result)

None


In [ ]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)

### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [32]:
# функция, решающая задачу с помощью NumPy
from copy import copy

def np_transformation(X, a=1):
  result = np.copy(X)

  result[1::2] = a

  result[::2] = result[::2] ** 3

  reversed_result = result[::-1]

  final_result = np.concatenate((X, reversed_result))

  return final_result
X = np.array([100, 200, 300, 400, 500])
result = np_transformation(X)
print(result)

[      100       200       300       400       500 125000000         1
  27000000         1   1000000]


In [33]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)

CPU times: user 417 µs, sys: 67 µs, total: 484 µs
Wall time: 496 µs
